image: alpine/latest
packages:
  - curl
  - nodejs
  - shellcheck
sources:
  - https://git.sr.ht/~rasch/shell-emoji
environment:
  project: shell-emoji
secrets:
  - 5fa223dd-4b6c-4e5a-93d8-8c6ce1b975b6 # sourcehut builds token
tasks:
  - build: |
      cd "$project"
      node generate.js > "$project"
  - validate: |
      cd "$project"
      shellcheck --shell=sh "$project"
      . "$project"
      test "$e_tada $e_melting_face" = '🎉 🫠'
  - stop_if_not_release: |
      cd "$project"
      git describe --exact-match HEAD || complete-build
  - release: |
      cd "$project"
      tag=$(git describe --exact-match HEAD)
      mv "$project" "$project-$tag"
      gzip -9 "$project-$tag"
      set +x
      . ~/.env
      curl --silent \
        --request POST \
        --header "Authorization: token $token" \
        --form "file=@$project-$tag.gz" \
        "https://git.sr.ht/api/repos/$project/artifacts/$tag"
